version: '3'
services:
    
    api-nginx:
        build:
            context: ./api/docker
            dockerfile: nginx.docker
        volumes:
            - ./api:/var/www/api
        ports:
            - "8080:80"
        depends_on:
            - api-php-fpm
    
    api-php-fpm:
        build:
            context: ./api/docker
            dockerfile: php-fpm.docker
        environment:
            APP_DEBUG: 1
        volumes:
            - ./api:/var/www/api
        depends_on:
            - api-postgres
            - api-mailer
            
    api-php-cli:
        build:
            context: ./api/docker
            dockerfile: php-cli.docker
        environment:
            APP_DEBIG: 1
        volumes:
            - ./api:/var/www/api
            - composer:/root/.composer/cache
        working_dir: /var/www/api
        tty: true
        depends_on:
            - api-postgres
            - api-mailer

    api-postgres:
        image: postgres:9.6-alpine
        volumes:
            - ./api/var/docker/postgres:/var/lib/postgresql/data
        environment:
            - "POSTGRES_USER=api"
            - "POSTGRES_PASSWORD=secret"
            - "POSTGRES_DB=api"
        ports:
            - "54321:5432"

    frontend-server:
        build:
            context: ./frontend/docker
            dockerfile: frontend.docker
        ports:
            - "8081:81"
        volumes:
            - ./frontend:/var/www/frontend

    frontend-nodejs:
        image: node:10.11-jessie
        volumes:
            - ./frontend:/var/www/frontend
        working_dir: /var/www/frontend
        tty: true
            
            
    api-mailer:
        image: mailhog/mailhog
        restart: unless-stopped
        ports:
            - "1025:1025"
            - "8082:8025"
            
    
          
volumes:
    composer:
         
    
